USE [master]
GO

/****** Object:  Database [CollegeDB]    Script Date: 5/3/2019 8:40:18 AM ******/
CREATE DATABASE [CollegeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CollegeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\CollegeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CollegeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS01\MSSQL\DATA\CollegeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CollegeDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CollegeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CollegeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CollegeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CollegeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CollegeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CollegeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CollegeDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CollegeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CollegeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CollegeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CollegeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CollegeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CollegeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CollegeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CollegeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CollegeDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CollegeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CollegeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CollegeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CollegeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CollegeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CollegeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CollegeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CollegeDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CollegeDB] SET  MULTI_USER 
GO

ALTER DATABASE [CollegeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CollegeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CollegeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CollegeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CollegeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CollegeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CollegeDB] SET  READ_WRITE 
GO


